In [ ]:
#variable
a=10
print("I am", a, "years old ")

I am 10 years old 


In [ ]:
#arithmetic operations on two integer variables
a=int(input("Enter a:"))
b=int(input("Enter b:"))
print("sum :",a+b)
print("differnce : ",a-b)
print("product is: ",a*b)
print("quotient is: ",a/b)
print("remainder is: ",a%b)
print("power is: ",a**b)
print("floor division is: ",a//b)

Enter a:32
Enter b:7
sum : 39
differnce :  25
product is:  224
quotient is:  4.571428571428571
remainder is:  4
power is:  34359738368
floor division is:  4


In [ ]:
#take salary from user,if the salary is more than 50000 there is 10% tax print his final salary

s=int(input("enter salary"))
if(s>=50000):
   s-=s*(0.1)
   print("final salary is: ",s);
else:
  print("there is no tax deduction ")

enter salary75000
final salary is:  67500.0


In [ ]:
#get the salary from the user if the salary is more than or equal to 50k apply 10% tax deduction ,if the salarty is less than 50k apply 5% tax ,if the salary is more than 70k apply 12% tax,if salary exceeds 100k print you are promited to next level
s=int(input("enter salary"))
if s==0:
  print("enter valid salarry")
elif(s<50000):
  print("salary is: ",s-s*(0.05))
elif(s<=70000):
   print("final salary is: ",s-s*(0.1))
elif(s<=100000):
  print("final salary is: ",s-s*(0.12))
else:
  print("you are promoted")

enter salary200000
you are promoted


In [ ]:
#for loop
r=range(1,11)
n=int(input("enter number:"))
for i in r:
  print(n,"x",i,"=",i*n)


enter number:101
101 x 1 = 101
101 x 2 = 202
101 x 3 = 303
101 x 4 = 404
101 x 5 = 505
101 x 6 = 606
101 x 7 = 707
101 x 8 = 808
101 x 9 = 909
101 x 10 = 1010


In [ ]:
#while loop
n=int(input("enter n"))
i=1
while(i<11):
  print(n,"x",i,"=",i*n)
  i+=1

enter n45
45 x 1 = 45
45 x 2 = 90
45 x 3 = 135
45 x 4 = 180
45 x 5 = 225
45 x 6 = 270
45 x 7 = 315
45 x 8 = 360
45 x 9 = 405
45 x 10 = 450


In [ ]:
#list hetrogenous
l1=[1,2.5,"apple",True]
print(l1[::1])

[1, 2.5, 'apple', True]


In [ ]:
#mutable:
l1.append('a')     #list name.append(element)-->adds elements at the back of the list
print(l1)
l1.insert(4,"hi")  #listname.insert(index,element)-->inserts element "hi" in the index 4
print(l1)

[1, 2.5, 'apple', True, 'a']
[1, 2.5, 'apple', True, 'hi', 'a']


In [ ]:
#adding 2 lists
l2=['&','@',123,"mango"]
l1.extend(l2)      #list1.extend(list2)-->l1=l1+l2
print(l1)

[1, 2.5, 'apple', True, 'hi', 'a', '&', '@', 123, 'mango']


In [ ]:
#remove
l1.remove("apple")   #list name.remove(element)-->removes the given element in list l1
l1.pop(3)            #list name.pop(index)-->pops the element which is at index given in list l1
print(l1)

[1, 2.5, True, 'a', '&', '@', 123, 'mango']


In [ ]:
#clear
l1.clear() #list name.clear()-->clears the list
print(l1)

[]


In [ ]:
#create a list of 10 integer elements print their squares save these squares in new list
l=[1,10,12,345,23,67,123,78,988,86]
l2=[]
for i in l:
  l2.append(i**2)
print(l2)


[1, 100, 144, 119025, 529, 4489, 15129, 6084, 976144, 7396]


In [ ]:
#list comprehension
#newlist=[output for if ]
l1=[1,10,12,345,23,67,123,78,988,86]
l2=[i*i for i in l1 if i>50]
print(l2)


[119025, 4489, 15129, 6084, 976144, 7396]


In [ ]:
#list comprehension
#newlist=[(st of if) if (cond) else (st of else) for  ]
l1=[1,10,12,345,23,67,123,78,988,86]
l2=[i*i if i>50 else 'x' for i in l1]
print(l2)

['x', 'x', 'x', 119025, 'x', 4489, 15129, 6084, 976144, 7396]


In [ ]:
#take the salary from the user if salary is less than 50k 10% tax otherwise 15%tax
l1=[55000,75000,10000,90000]
l=[n-(n*0.1) if(n<=50000) else n-(n*0.15) for n in l1]
print(l)

[46750.0, 63750.0, 9000.0, 76500.0]


In [2]:
#tuples
t=(12,43,6.45,"apple")
for i in t:     #display elements in the tuples using loop
  print(i)

12
43
6.45
apple


In [6]:
print(t)    #original array
print(t[::-1]) #tuple slicing

(12, 43, 6.45, 'apple')
('apple', 6.45, 43, 12)


In [12]:
t1=(21,56,4,23,89)
s=sorted(t1) #sorted
print(s)
s.pop()     #pop
print(s)

[4, 21, 23, 56, 89]
[4, 21, 23, 56]


In [13]:
l=[1,23,4,5,6,7]
print(l)    #list
print(tuple(l))   #tuple

[1, 23, 4, 5, 6, 7]
(1, 23, 4, 5, 6, 7)


In [14]:
z=zip(t1,l)
print(tuple(z))

((21, 1), (56, 23), (4, 4), (23, 5), (89, 6))


In [17]:
#concatnation of tuples
print(t+t)

(12, 43, 6.45, 'apple', 12, 43, 6.45, 'apple')


In [24]:
#tuple comprehension
t=(1,23,55,67,88,99,22,23,55)
l=[i for i in t if i%11==0]
print(tuple(l))

(55, 88, 99, 22, 55)


In [25]:
print(t.count(23))

2


In [28]:
print(max(t)) #maximum elements
print(min(t)) #minimum elements

99
1


In [29]:
#sets
s1={1,23,45,1,23,67,89}   #prints the unique elements
print(s1)

{1, 67, 23, 89, 45}


In [34]:
s2={1,23,1,67,89}
print(s1.union(s2)) #union

{1, 67, 45, 23, 89}


In [31]:
print(s2.intersection(s1))  #intersection

{89, 67, 1, 23}


In [36]:
print(s1.difference(s2))    #difference

{45}


In [43]:
s1.update(s2)
print(s1)

{1, 67, 45, 23, 89}


In [44]:
s1.add(234)
print(s1)

{1, 67, 234, 45, 23, 89}


In [ ]:
# create a dictionary
dict1={"mentor":'jwalitha',"mentor":'likhita',35:'ramya',36:'lavanya',71:"dhanush"}
print(dict1)

{'mentor': 'likhita', 35: 'ramya', 36: 'lavanya', 71: 'dhanush'}


In [ ]:
#accessing keys and values from dictionary
print(dict1.keys())
print(dict1.values())
print(dict1[36])

dict_keys(['mentor', 35, 36])
dict_values(['likhita', 'ramya', 'lavanya'])
lavanya


In [ ]:
#nested dictionary
dict3={"dept":"CSE","details":{"year":"II","sec":"D","count":71}}
print("year is ",dict3["details"]["year"])
print("section is ",dict3["details"]["sec"])
print("count is ",dict3["details"]["count"])

year is  II
section is  D
count is  71


In [ ]:
#combine the 2 lists by zip function
l1=[1,23,45]
l2=["ramya","likhita","lav"]
z=zip(l1,l2)
for i in z:
  print(i)

(1, 'ramya')
(23, 'likhita')
(45, 'lav')


In [ ]:
#creates a dictionary from two lists
l1=[1,23,45]
l2=["ramya","likhita","lav"]
print(dict(zip(l1,l2)))

{1: 'ramya', 23: 'likhita', 45: 'lav'}


In [ ]:
#numpy
import numpy as np
A=np.array([1,2,3,4])   #1-d array
print(A.ndim)           # (columns,)
print(A.shape)

1
(4,)


In [ ]:
B=np.array([[1,2,3],[4,5,6]]) #2-d array
#elements in each row=columns
print(B)
print(B.ndim)   #2-d array
print(B.shape)  # (rows,columns)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:
#creating 3-d array
C=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[56,76,6]]])
print(C)
print(C.ndim)   #3-d array
print(C.shape)  #(groups,rows,columns)   #no.of elements=groups*rows*columns

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [56 76  6]]]
3
(2, 2, 3)


In [ ]:
#for ones
m=np.ones((3,4,3))    #g,r,c
print(m)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#for zeros
m=np.zeros((3,4,3))    #g,r,c
print(m)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A=np.arange(1,10,2)     #start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by 8 using arange function between 1 and 1000
A=np.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
#linspace-->spliting a range into n numbers with common differences
A=np.linspace(48,58,11)
print(A)

[48. 49. 50. 51. 52. 53. 54. 55. 56. 57. 58.]


In [ ]:
#study tuples and sets,documentation,qr codes task