In [94]:
import numpy as np
A=np.arange(1,13).reshape(4,3)
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
A=np.linspace(2,4,8).reshape(4,2)
print(A)

[[2.         2.28571429]
 [2.57142857 2.85714286]
 [3.14285714 3.42857143]
 [3.71428571 4.        ]]


In [11]:
A=np.array([12,32,4,6,45,65,78,1]).reshape(2,2,2)
print(A)

[[[12 32]
  [ 4  6]]

 [[45 65]
  [78  1]]]


In [12]:
B=np.array([12,32,4,6,45,65,78,1]).reshape(2,2,2)
B.resize(2,2,2) #resizes-changes the shape of original array
#reshape- changes needs saving in another variable
print(B)

[[[12 32]
  [ 4  6]]

 [[45 65]
  [78  1]]]


In [15]:
#array operations
A=np.array([23,45,76,1])
B=np.array([8,25,6,2])
C=A-B   # a list will throw an error while arrays iterate themselves
print(C)
print(A-B)

[15 20 70 -1]
[15 20 70 -1]


In [16]:
#array operations
A=np.array([23,45,76,1])
B=np.array([8,25,6,2])
C=A+B   # a list will throw an error while arrays iterate themselves
print(A+B)


[31 70 82  3]


In [23]:
#array operations
A=np.array([23,45,76,1]).reshape(2,2)
B=np.array([8,25,6,2]).reshape(2,2)
print(A)
print("___________________________")
print(B)
C=A*B   #one on one multiplication
print("___________________________")
print(C)

[[23 45]
 [76  1]]
___________________________
[[ 8 25]
 [ 6  2]]
___________________________
[[ 184 1125]
 [ 456    2]]


In [22]:
#array operations
A=np.array([23,45,76,1]).reshape(2,2)
B=np.array([8,25,6,2]).reshape(2,2)
print(A)
print("___________________________")
print(B)
C=A@B   #matrix  multiplication
print("___________________________")
print(C)

[[23 45]
 [76  1]]
___________________________
[[ 8 25]
 [ 6  2]]
___________________________
[[ 454  665]
 [ 614 1902]]


In [24]:
#array operations
A=np.array([23,45,76,1]).reshape(2,2)
B=np.array([8,25,6,2]).reshape(2,2)
print(A)
print("___________________________")
print(B)
C=A.dot(B)   #matrix  multiplication
print("___________________________")
print(C)

[[23 45]
 [76  1]]
___________________________
[[ 8 25]
 [ 6  2]]
___________________________
[[ 454  665]
 [ 614 1902]]


In [25]:
A=np.array([12,43,5,12,98]) #integers
print(A.max())
print(A.min())

98
5


In [27]:
A=np.array([12.45,43.567,5.43,12.789,98.89])  #floating points
print(A.max())
print(A.min())

98.89
5.43


In [31]:
#array operations
A=np.array([23,45,98,101,456,12,4,123,86,90,453,2]).reshape(4,3)
print(A)
print("___________________________")
print(A.max(axis=0))    #axis 0 - column
print("___________________________")
print(A.max(axis=1))    #axis 1 -row

[[ 23  45  98]
 [101 456  12]
 [  4 123  86]
 [ 90 453   2]]
___________________________
[101 456  98]
___________________________
[ 98 456 123 453]


In [32]:
#array operations
A=np.array([23,45,98,101,456,12,4,123,86,90,453,2]).reshape(4,3)
print(A)
print("___________________________")
print(A.min(axis=0))    #axis 0 - column
print("___________________________")
print(A.min(axis=1))    #axis 1 -row

[[ 23  45  98]
 [101 456  12]
 [  4 123  86]
 [ 90 453   2]]
___________________________
[ 4 45  2]
___________________________
[23 12  4  2]


In [34]:
#array operations
A=np.array([23,45,76,1]).reshape(2,2)
B=np.array([8,25,6,2]).reshape(2,2)
print(A)
print("___________________________")
print(B)
print("After vertical stacking the array is")
print(np.vstack((A,B)))

[[23 45]
 [76  1]]
___________________________
[[ 8 25]
 [ 6  2]]
After v stacking the arrays
[[23 45]
 [76  1]
 [ 8 25]
 [ 6  2]]


In [35]:
#array operations
A=np.array([23,45,76,1]).reshape(2,2)
B=np.array([8,25,6,2]).reshape(2,2)
print(A)
print("___________________________")
print(B)
print("After horizontal stacking the array is")
print(np.hstack((A,B)))

[[23 45]
 [76  1]]
___________________________
[[ 8 25]
 [ 6  2]]
After horizontal stacking the array is
[[23 45  8 25]
 [76  1  6  2]]


In [40]:
#joining arrays
#array operations
A=np.array([23,45,76,1]).reshape(2,2)
B=np.array([8,25,6,2]).reshape(2,2)
print(A)
print("___________________________")
print(B)
print("After vertical stacking the array is")
print(np.stack((A,B),axis=0))

[[23 45]
 [76  1]]
___________________________
[[ 8 25]
 [ 6  2]]
After vertical stacking the array is
[[[23 45]
  [76  1]]

 [[ 8 25]
  [ 6  2]]]


In [44]:
A=np.arange(30).reshape(2,3,5)
print(A)                         #stacks according to the dimension
print("After dstack")             #no of row == no.of groups
#no .of columns in every group == no.of rows in every group
#[0,0],[1,1],............
print(np.dstack(A))          # original   (groups,rows,columns)
                                #after dstack (columns,groups,rows)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]
(2, 3, 5)


In [47]:
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")    #splits the array vertically into equal halves
np.vsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [48]:
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,(2,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [50]:
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [54]:
A=np.arange(18).reshape(3,6)
print(A)
print("After splitting")    #splits the array horizontally into equal halves
np.hsplit(A,3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [56]:
A=np.arange(18).reshape(3,6)
print(A)
print("After splitting")
np.hsplit(A,(2,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [57]:
A=np.array([12,54,77,2])
print(A)
print(A.argmax())           #argmax returns the position of the maximum element in the given array

[12 54 77  2]
2


In [63]:
A=np.array([12,453,575,2,4,98,123,65,77,44,89,66]).reshape(4,3)
print(A)                 #  columns                rows
print(A.argmax(axis=0))  # 0  0     0            0   1   2
                         # 1   1     1           0   1   2
                         # 2   2     2           0   1   2
print(A.argmax(axis=1))

[[ 12 453 575]
 [  2   4  98]
 [123  65  77]
 [ 44  89  66]]
[2 0 0]
[2 2 0 1]


In [61]:
A=np.array([12,54,77,2])
print(A)
print(A.argmin())    #argmin returns the position of the minimum element in the given array

[12 54 77  2]
3


In [64]:
#NUMPY STATISTICS
#mean ,medain,standard deviation,variance
A=np.array([12,34,56,78,89])
print("mean= ",np.mean(A))
print("median= ",np.median(A))
print("standard deviation= ",np.std(A))
print("variance= ",np.var(A))

mean=  53.8
median=  56.0
standard deviation=  28.173746644704533
variance=  793.76


In [65]:
#TRIGNOMETRY
A=np.pi
print(A)    #radians

3.141592653589793


In [67]:
np.rad2deg(A)     #radians to degree

180.0

In [68]:
A=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])       #radians
print(A)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [69]:
print(np.rad2deg(A))      #degree

[ 45.  60.  90. 180.]


In [73]:
C=np.array([0,30,45,60,90,120,180])
B=np.deg2rad(C)
print(B)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [74]:
np.sin(C)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [75]:
np.cos(C)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [76]:
np.tan(C)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [83]:
np.arcsin(1)        #sin^-1

1.5707963267948966

In [84]:
np.arccos(1)    #cos^-1

0.0

In [85]:
np.arctan(1)    #tan^-1

0.7853981633974483

In [87]:
a=6
b=8
print(np.hypot(a,b))    #hypotnous

10.0


In [88]:
A=np.array([12,45,2,67,23])
print(np.where(A>50)) #returns the position of the elements according to the condition

(array([3]),)


In [89]:
A=np.array([12,45,2,67,23,45])
print(np.where(A==45))      #returns the position of the searching element

(array([1, 5]),)


In [90]:
A=np.array([12,45,2,67,23,45])
print(np.where(A%2==0))      #returns the position of the even elements

(array([0, 2]),)


In [108]:
A=np.array([12,23,34,45,21,45])   #12 21 23 34 45 45
print(np.searchsorted(A,34))      #output the index of the seach element after sorting the list

2


In [110]:
#linear alzebra
A=np.array([6,34,2,67,8])
B=np.array([5,12,4,1,3])
print(np.add(A,B))                #addition of 2 arrays
print(np.subtract(A,B))            #subtraction

[11 46  6 68 11]
[ 1 22 -2 66  5]


In [111]:
print(np.divide(A,B))       #quotient

[ 1.2         2.83333333  0.5        67.          2.66666667]


In [112]:
print(np.mod(A,B))        #remainder

[ 1 10  2  0  2]


In [113]:
print(np.divmod(A,B))     # both quotient and remainder

(array([ 1,  2,  0, 67,  2]), array([ 1, 10,  2,  0,  2]))


In [115]:
A=np.array([6,34,2,67,8])
print(np.diff(A))

[ 28 -32  65 -59]


In [114]:
#sort
A=np.array([6,34,2,67,8])
print(np.sort(A))

[ 2  6  8 34 67]


In [117]:
#set functions
A=np.array([6,34,2,67,8])
B=np.array([5,12,4,1,3])
print(np.union1d(A,B))

[ 1  2  3  4  5  6  8 12 34 67]


In [123]:
A=np.array([6,34,2,67,8])
B=np.array([5,12,4,1,2,3])
print(np.intersect1d(A,B))

[2]


In [125]:
A=np.array([6,34,2,67,8])
B=np.array([5,12,4,1,3])
print(np.setdiff1d(A,B))

[ 2  6  8 34 67]


In [126]:
#Rounding !

print(np.trunc([-3.11234,4.235767]))

[-3.  4.]


In [127]:
print(np.floor([-3.11234,4.235767]))

[-4.  4.]


In [128]:
print(np.ceil([-3.11234,4.235767]))

[-3.  5.]


In [129]:
print(np.fix([-3.11234,4.235767]))

[-3.  4.]


In [134]:
a=np.around(-3.11234, 3)
print(a)

-3.112


In [136]:
#more functions
A=np.array([3,4,12,45,67])      #cumulative sum
print(np.cumsum(A))

[  3   7  19  64 131]


In [138]:
A=np.array([3,4,12,45,67])      #cumulative product
print(np.cumprod(A))

[     3     12    144   6480 434160]


In [143]:
print(np.lcm(48,6))     #lcm
print(np.gcd(48,6))     #gcd

48
6


In [146]:
Ar=np.array([24,45,23])
print(np.lcm.reduce(Ar))    #lcm for array of elements using reduce
print(np.gcd.reduce(Ar))    #gcd for array of elements using reduce

8280
1


In [148]:
#inverse of the matrix

a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [150]:
from numpy import random as rd


In [154]:
A=rd.rand() #n #default limit 0 to 0.99
print(A)

0.5487929546383712


In [153]:
print(rd.rand(10))    # displays the 10 random numbers with the range 0 to 0.99

[0.09075095 0.73104371 0.55430186 0.03813712 0.0171737  0.44240796
 0.20046468 0.70361713 0.54220062 0.76582981]


In [161]:
A=rd.randint(4) #randint(limit)==> limit 0,1,2,,3,4
print(A)

2


In [162]:
A=rd.randint(50,size=6) #limit with size
print(A)

[34 41 49 10  5 21]


In [163]:
A=rd.randint(50,size=(2,3)) #limit with shape
print(A)

[[11 29 19]
 [39 10 15]]


In [164]:
#Joins
A=np.array([1,2,3])
B=np.array([4,5,6])
# 1*4 +2*5 +3*6
print(np.inner(A,B))

32


In [165]:
#Joins
A=np.array([1,2,3])
B=np.array([4,5,6])
# 1X(4,5,6)+2(4,5,6)+3(4,5,6)
print(np.outer(A,B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [166]:
#Joins
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.cross(A,B))

[-3  6 -3]
